spring:
  application:
    name: my-mcp

  datasource:
    url: jdbc:mysql://localhost:3306/search-service
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   
    show-sql: true    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  ai:
    mcp:
      server:
        name: my-mcp-server
        version: 1.0.0

logging:
  pattern:
    console: 
